//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace controle_de_tarefas {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("controle_de_tarefas.MenuMessages", typeof(MenuMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1 - Adicionar tarefa.
        /// </summary>
        internal static string opcao1MenuPrincipal {
            get {
                return ResourceManager.GetString("opcao1MenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1 - ID: Remove apenas a tarefa com o ID informado.
        /// </summary>
        internal static string opcao1MenuRemoverTarefa {
            get {
                return ResourceManager.GetString("opcao1MenuRemoverTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 2 - Remover tarefa.
        /// </summary>
        internal static string opcao2MenuPrincipal {
            get {
                return ResourceManager.GetString("opcao2MenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 2 - Nome: Remove todas as tarefas com o nome informado.
        /// </summary>
        internal static string opcao2MenuRemoverTarefa {
            get {
                return ResourceManager.GetString("opcao2MenuRemoverTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 3 - Listar todas as tarefas.
        /// </summary>
        internal static string opcao3MenuPrincipal {
            get {
                return ResourceManager.GetString("opcao3MenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 3 - Data: Remove todas as tarefas com a data informada.
        /// </summary>
        internal static string opcao3MenuRemoverTarefa {
            get {
                return ResourceManager.GetString("opcao3MenuRemoverTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 4 - Buscar tarefa específica.
        /// </summary>
        internal static string opcao4MenuPrincipal {
            get {
                return ResourceManager.GetString("opcao4MenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 4 - Voltar ao menu principal.
        /// </summary>
        internal static string opcao4MenuRemoverTarefa {
            get {
                return ResourceManager.GetString("opcao4MenuRemoverTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5 - Sair.
        /// </summary>
        internal static string opcao5MenuPrincipal {
            get {
                return ResourceManager.GetString("opcao5MenuPrincipal", resourceCulture);
            }
        }
    }
}
